# This is a basic workflow to help you get started with Actions

# CI名称
name: PPL_TEST

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - master
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Prepare Test Env
        run: |
          cp ../../ppltest.py ./
          cp ../../test_ppl.py ./
          #pip install pytest
          
      # ppl build
      - name: ppl build
        run: |
          pytest test_ppl.py::test_build_ppl
          
      # ppl x86 test
      - name: ppl x86 test
        run: |
          pytest test_ppl.py::test_ppl_x86
          
      # ppl cuda test
      - name: ppl cuda test
        run: |
          pytest test_ppl.py::test_ppl_cuda
          
          
          
