# CI名称
name: ppl_x86_quick_test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - master
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ GITHUB_RUN_ID }}
      
      # Runs a set of commands using the runners shell
      #- name: Build
      #  run: |
      #    source /opt/rh/devtoolset-9/enable
      #    ./build-for-test.sh x64
      
      #- name: quick test
      #  uses: actions/checkout@v2
      #  with:
      #    path: $GITHUB_RUN_ID
      
  
